### PR TITLE
Add a darker chocolate node

### PR DESCRIPTION
**Pull request by HybridDog**
See #1
It's not that dark, so l called it medium chocolate block and renamed the other one to milk chocolate block.
l didn't add a dark chocolate egg because l didn't encounter one in real life yet.

### CODE REVIEW

**Comment by iisu** [comment]
It looks pretty dark to me though.
We need a dark chocolate egg for crafting dark chocolate blocks.
Eggs are given to the player in some way (by default dropped on the ground so the player can find them and take them) and blocks should be obtained by crafting the eggs.

PS, fix your formatting. You just changed one line and added four and look how many lines got changed (mostly empty lines).

**Comment by HybridDog** [comment]
> You just changed one line and added four and look how many lines got changed (mostly empty lines).

l configured geany to automatically remove trailing whitespace.
Here's the commit without whitespace removals: https://github.com/iisu/minetest-easter-eggs/pull/2/files?w=1

**Comment by iisu** [comment]
There's no need to use the word "medium". It's just a regular chocolate and just calling it "chocolate" is enough.

I have three ideas. I'll start with my least preferable.
1. Just call your block "dark chocolate". You can make it darker if you want but I think what it is now is good. My block stays "chocolate".

2. Let's call my block "milk chocolate" and yours "chocolate". We need a third texture for "dark chocolate". I would rather have only 2 kinds of chocolate though.

3. Replace my texture with yours and add "dark chocolate". I actually like your texture more than mine and you're right that mine looks more milky. Keeping my texture as "milk chocolate" would mean the first idea and as I said, we don't need 3 nodes.
Your texture for "chocolate" and a new darker one for "dark chocolate".

If you chose option 2 or 3 but don't want to make yet another texture, tell me. Then I'll make it once this pull request gets resolved.

**Comment by HybridDog** [comment]
l thought that it's just my perception, but now l see that l lost the dark texture. l don't know how this happened, maybe l accidentally hit ctrl+s in the wrong moment before closing gimp.
dark:
screenshot_20170415_180036
this PR (the right one):
screenshot_20170416_091653

**Pull request closed without merging**
